name: Android Build

on:
  push:
    branches:
      - OwlProxy-app
  workflow_dispatch:

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build release APK
        run: ./gradlew :app:assembleRelease

      - name: List release APKs
        run: ls app/build/outputs/apk/release/

      - name: Upload release APK
        uses: actions/upload-artifact@v4
        with:
          name: OwlProxy-Release
          path: app/build/outputs/apk/release/*.apk
